# What do want?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: local #Use to bind Persistent Volume to Persistent Volume Claim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
# How do we want it implemented
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  storageClassName: local #Use to bind Persistent Volume to Persistent Volume Claim
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/some new/directory/structure/"
    type: DirectoryOrCreate

---    
# What do want?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
spec:
  storageClassName: local-elasticsearch #Use to bind Persistent Volume to Persistent Volume Claim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
# How do we want it implemented
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-elasticsearch-storage
spec:
  storageClassName: local-elasticsearch #Use to bind Persistent Volume to Persistent Volume Claim
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/elasticsearch/data/"
    type: DirectoryOrCreate      